---
deployment:
  tasks:
    - export DEPLOYPATH=/home/muhosting/public_html/
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp competition.php $DEPLOYPATH
    - /bin/cp events.php $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp register.php $DEPLOYPATH
    - /bin/cp scratch_prep.php $DEPLOYPATH
    - /bin/cp subscribe.php $DEPLOYPATH
    - /bin/cp -Rf admin $DEPLOYPATH
    - /bin/cp -Rf archive $DEPLOYPATH
    - /bin/cp -Rf assets $DEPLOYPATH
    - /bin/cp -Rf css $DEPLOYPATH
    - /bin/cp -Rf include $DEPLOYPATH
    - /bin/cp -Rf js $DEPLOYPATH
    - /bin/cp -Rf lib $DEPLOYPATH
    - /bin/cp -Rf php $DEPLOYPATH
